export const sizeVariant = [
  {
    childId: '943679',
    inStock: true,
    name: "Puma Nrgy Neko Turbo Men'S Running Shoes - 6",
    packSize: 'UK 6',
    quantity: 22,
    sku: '4015268606563',
    variantName: 'UK 6',
    imageUrl: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/a/c/acb4c8e19252001_1.jpg',
    isLux: 0,
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '943680',
    inStock: false,
    name: "Puma Nrgy Neko Turbo Men'S Running Shoes - 7",
    packSize: 'UK 7',
    quantity: 0,
    sku: '4015268606587',
    variantName: 'UK 7',
    imageUrl: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/9/7/9716c8e19252001_1.jpg',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '943681',
    inStock: true,
    name: "Puma Nrgy Neko Turbo Men'S Running Shoes - 8",
    packSize: 'UK 8',
    quantity: 100,
    sku: '4015268606600',
    variantName: 'UK 8',
    imageUrl: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/e/3/e3aec8e19252001_1.jpg',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '943682',
    inStock: true,
    name: "Puma Nrgy Neko Turbo Men'S Running Shoes - 9",
    packSize: 'UK 9',
    quantity: 139,
    sku: '4015268606624',
    variantName: 'UK 9',
    imageUrl: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/4/3/43aec8e19252001_1.jpg',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '943683',
    inStock: true,
    name: "Puma Nrgy Neko Turbo Men'S Running Shoes - 10",
    packSize: 'UK 10',
    quantity: 70,
    sku: '4015268606648',
    variantName: 'UK 10',
    imageUrl: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/0/e/0e3dc8e19252001_1.jpg',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '943684',
    inStock: true,
    name: "Puma Nrgy Neko Turbo Men'S Running Shoes - 11",
    packSize: 'UK 11',
    quantity: 68,
    sku: '4015268606662',
    variantName: 'UK 11',
    imageUrl: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/3/2/32d6c8e19252001_1.jpg',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '943685',
    inStock: false,
    name: "Puma Nrgy Neko Turbo Men'S Running Shoes - 12",
    packSize: 'UK 12',
    quantity: 0,
    sku: '4015268606686',
    variantName: 'UK 12',
    imageUrl: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/f/0/f06ad8c19252001.jpg',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '943686',
    inStock: false,
    name: "Puma Nrgy Neko Turbo Men'S Running Shoes - 13",
    packSize: 'UK 13',
    quantity: 0,
    sku: '4015268606693',
    variantName: 'UK 13',
    imageUrl: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/2/4/2416d8c19252001.jpg',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
];

export const currentVariantSize = {
  childId: '943679',
  inStock: true,
  name: "Puma Nrgy Neko Turbo Men'S Running Shoes - 6",
  packSize: 'UK 6',
  quantity: 22,
  sku: '4015268606563',
  variantName: 'UK 6',
  imageUrl: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/a/c/acb4c8e19252001_1.jpg',
  contentLang: {
    name: 'en',
    price_description: 'en',
    button_text: 'en',
    message_on_return: 'en',
  },
};

export const shadeVariant = [
  {
    childId: '520726',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 238 Rich Tan',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395742357_238richtan.jpg',
    quantity: 1425,
    sku: '6902395742357',
    variantName: '238 Rich Tan',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520728',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 320 Natural Tan',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395742401_320naturaltan.jpg',
    quantity: 675,
    sku: '6902395742401',
    variantName: '320 Natural Tan',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520719',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Clay - 125 Nude Beige',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395646891_125nudebeige.jpg',
    quantity: 1014,
    sku: '6902395646891',
    variantName: '125 Nude Beige',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520725',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 235 Pure Beige With Clay',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395646969_235purebeige.jpg',
    quantity: 1269,
    sku: '6902395646969',
    variantName: '235 Pure Beige',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520716',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Clay - 115 Ivory',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395646860_115ivory.jpg',
    quantity: 1922,
    sku: '6902395646860',
    variantName: '115 Ivory',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520730',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 332 Golden Caramel With Clay',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395742432_332goldencaramel.jpg',
    quantity: 2530,
    sku: '6902395742432',
    variantName: '332 Golden Caramel',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520731',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 335 Classic Tan',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395742449_335classictan.jpg',
    quantity: 631,
    sku: '6902395742449',
    variantName: '335 Classic Tan',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520717',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation Whit Clay SPF 22 - 118 Light Beige',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395735151_118lightbeige.jpg',
    quantity: 1551,
    sku: '6902395735151',
    variantName: '118 Light Beige',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520722',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Clay - 220 Natural Beige',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395646921_220naturalbeige.jpg',
    quantity: 168,
    sku: '6902395646921',
    variantName: '220 Natural Beige',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520727',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 310 Sun beige',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395646983_310sunbeige.jpg',
    quantity: 4097,
    sku: '6902395646983',
    variantName: '310 Sun Beige',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520720',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Clay - 128 Warm Nude',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395718338_128warmnude.jpg',
    quantity: 3360,
    sku: '6902395718338',
    variantName: '128 Warm Nude',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520732',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 338 Spicy Brown',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395742456_338spicybrown.jpg',
    quantity: 795,
    sku: '6902395742456',
    variantName: '338 Spicy Brown',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520733',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 340 Cappuccino',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395735175_340cappuccino.jpg',
    quantity: 477,
    sku: '6902395735175',
    variantName: '340 Cappuccino',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520721',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 130 Buff Beige',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395742203_130buffbeige.jpg',
    quantity: 2075,
    sku: '6902395742203',
    variantName: '130 Buff Beige',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520723',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 228 Soft Tan',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395742302_228softtan.jpg',
    quantity: 1005,
    sku: '6902395742302',
    variantName: '228 Soft Tan',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520729',
    inStock: true,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation - 330 Toffee',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395718383_330toffee.jpg',
    quantity: 279,
    sku: '6902395718383',
    variantName: '330 Toffee',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520718',
    inStock: false,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 120 Classic Ivory',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395646877_120classicivory.jpg',
    quantity: 0,
    sku: '6902395646877',
    variantName: '120 Classic Ivory',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520724',
    inStock: false,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 230 Natural Buff',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395646952_230naturalbuff.jpg',
    quantity: 0,
    sku: '6902395646952',
    variantName: '230 Natural Buff',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
  {
    childId: '520725',
    inStock: false,
    name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 230 Natural Buff',
    shadeImage: 'https://images-static.nykaa.com/media/icons/6902395646952_230naturalbuff.jpg',
    quantity: 80,
    sku: '6902395646952',
    variantName: '230 Natural Buff',
    contentLang: {
      name: 'en',
      price_description: 'en',
      button_text: 'en',
      message_on_return: 'en',
    },
  },
];

export const currentShadeVariant = {
  childId: '520726',
  name: 'Maybelline New York Fit Me Matte+Poreless Liquid Foundation With Pump - 238 Rich Tan',
  offerPrice: 549,
  packSize: '30ml',
  shadeImage: 'https://images-static.nykaa.com/media/icons/6902395742357_238richtan.jpg',
  quantity: 1425,
  sku: '6902395742357',
  slug: 'maybelline-new-york-fit-me-matte-poreless-foundation/p/31074',
  variantName: '238 Rich Tan',
  imageUrl: 'https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/6/9/6902395742357.1.jpg',
  contentLang: {
    name: 'en',
    price_description: 'en',
    button_text: 'en',
    message_on_return: 'en',
  },
};
