const proRegistrationEvents = {
  FETCH_USER_INFO_PROGRESS: 'FETCH_USER_INFO_PROGRESS',
  FETCH_USER_INFO_SUCESS: 'FETCH_USER_INFO_SUCESS',
  FETCH_USER_INFO_ERROR: 'FETCH_USER_INFO_ERROR',
  POST_USER_INFO_INPROGRESS: 'POST_USER_INFO_INPROGRESS',
  POST_USER_INFO_ERROR: 'POST_USER_INFO_ERROR',
  POST_USER_BASIC_INFO: 'POST_USER_BASIC_INFO',
  POST_USER_ADDRESS_INFO: 'POST_USER_ADDRESS_INFO',
  POST_USER_ADDRESS_INFO_INPRORESS: 'POST_USER_ADDRESS_INFO_INPROGRESS',
  POST_USER_BUSINESS_INFO: 'POST_USER_BUSINESS_INFO',
  POST_USER_BUSINESS_INFO_INPROGRESS: 'POST_USER_BUSINESS_INFO_INPROGRESS',
  POST_USER_ID_DOCUMENT_INPROGRESS: 'POST_USER_ID_DOCUMENT_INPROGRESS',
  POST_USER_ID_DOCUMENT_UPLOAD: 'POST_USER_ID_DOCUMENT_UPLOAD',
  POST_USER_BUSINESS_DOCUMENT_INPROGRESS: 'POST_USER_BUSINESS_DOCUMENT_INPROGRESS',
  POST_USER_BUSINESS_DOCUMENT_UPLOAD: 'POST_USER_BUSINESS_DOCUMENT_UPLOAD',
  POST_USER_ID_DOCUMENT_REMOVE: 'POST_USER_ID_DOCUMENT_REMOVE',
  POST_USER_BUSINESS_DOCUMENT_REMOVE: 'POST_USER_BUSINESS_DOCUMENT_REMOVE',
  POST_USER_TERM_CONDITION_INPROGRESS: 'POST_USER_TERM_CONDITION_INPROGRESS',
  POST_USER_TERM_CONDITION: 'POST_USER_TERM_CONDITION',
};

export default proRegistrationEvents;
