export const ALL_WIDGETS_NAME = {
  PRIMARY_INFO: 'PRIMARY_INFO',
  BRAND_INFO: 'BRAND_INFO',
  CTA: 'CTA',
  DESCRIPTION_ATTRIBUTES: 'DESCRIPTION_ATTRIBUTES',
  MEDIA: 'MEDIA',
  COLORS: 'COLORS',
  SIZES: 'SIZES',
  SHADES: 'SHADES',
  TOP_REVIEW: 'TOP_REVIEW',
  META_INFO: 'META_INFO',
};

export const PLATFORM = {
  NYKAA: 'beauty',
  FASHION: 'fashion',
  MEN: 'men',
};
